###############

GPU: [0,1]

VERBOSE: True

MODEL:
  MODE: 'Denoising'
  SESSION: 'continued_2'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 8
  NUM_EPOCHS: 90
  LR_INITIAL: 2e-4
  #NEPOCH_DECAY: [40]
  #BETA1: 0.9

TRAINING:
  TRAIN_PS: 128
  VAL_PS: 196
  RESUME: True
  TRAIN_DIR: '../../datasets/SIDD_Small_patches/train' # path to training data
  VAL_DIR: '../../datasets/SIDD_Small_patches/val'     # path to validation data
  SAVE_DIR: './checkpoints'          # path to save models and images
  SAVE_IMAGES: False
  #VAL_AFTER_EVERY: 1
